#//////////////////////////////////////////////////////////////////////////////
# AG Development Framework.
# Copyright 2011-2020 GeorgeAth. All Rights Reserved.
#//////////////////////////////////////////////////////////////////////////////
name: Web

# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:
      - master

env:
  # Script configuration.
  AG_CI: 1
  AG_TARGET_ARGS: --ci --web

jobs:
  cmake-build-web:
    # Set job.Name.
    name: cmake-build-web
    # Set job.TargetOS.
    runs-on: ubuntu-latest

    steps:
    # Step : Checkout repository master branch.
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # Step : Download dependencies 1/2.
    - uses: actions/checkout@v1
      with:
        repository: GeorgeAth/AG-DEP
        ref: refs/heads/master
        token: ${{ secrets.agci }}
        fetch-depth: 1

    # Step : Download dependencies 2/2.
    - uses: actions/checkout@v1
      with:
        repository: GeorgeAth/AG-DEV
        ref: refs/heads/master
        token: ${{ secrets.agci }}
        fetch-depth: 1

    # Step : Checkout Emscripten.
    - uses: actions/checkout@v1
      with:
        repository: emscripten-core/emsdk
        ref: refs/heads/master
        fetch-depth: 1

    # Step : Run CI.
    - name: Run CI.
      shell: bash
      run: |
        pushd ../emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        popd
        build/run-ci.sh

    # Step : Upload artifacts.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_web
        path: ../.build/out/bin
