#//////////////////////////////////////////////////////////////////////////////
# AG Development Framework.
# Copyright 2011-2020 GeorgeAth. All Rights Reserved.
#//////////////////////////////////////////////////////////////////////////////
name: MacOS

# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:
      - master

env:
  # Script configuration.
  #AG_BUILD_TYPE: Release
  AG_BUILD_PATH: build_macos

jobs:
  cmake-build-macos:
    # Set job.Name.
    name: cmake-build-macos
    # Set job.TargetOS.
    runs-on: macos-latest

    steps:
    # Step : Checkout repository master branch.
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # Step : Download dependencies 1/2.
    - uses: actions/checkout@v1
      with:
        repository: GeorgeAth/AG-DEP
        ref: refs/heads/master
        token: ${{ secrets.agci }}
        fetch-depth: 1

    # Step : Download dependencies 2/2.
    - uses: actions/checkout@v1
      with:
        repository: GeorgeAth/AG-DEV
        ref: refs/heads/master
        token: ${{ secrets.agci }}
        fetch-depth: 1

    # Step : Run CI.
    - name: Run CI.
      shell: bash
      run: |
        build/run-ci.sh

    # Step : Upload artifacts.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_macos
        path: ../.build/out/bin
